[package]
edition = "2021"
name = "posts"
version = "0.0.1"

[lib]
crate-type = ["cdylib", "rlib"]
name = "posts"

[dependencies]
derive_more = "0"
serde = "1"

hdk = {version = "0.0.140"}
posts_zome = {path = "../../../zomes/posts"}
