[package]
edition = "2021"
name = "profiles"
version = "0.0.1"

[lib]
crate-type = ["cdylib", "rlib"]
name = "profiles"

[dependencies]
derive_more = "0"
serde = "1"

hdk = {version = "0.0.130", features = ["encoding"]}
profiles_zome = {path = "../../../zomes/profiles"}
